DROP TABLE l05_answer;

CREATE TABLE l05_answer(
	id NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 10) PRIMARY KEY,
	author VARCHAR2(50) NOT NULL,
	description VARCHAR2(1000) NOT NULL
);